
	$admin_email,
	$admin_password,
	$admin_realname,
	$create_htaccess = false,
	$webservergroup = 'apache',
 	$db_driver = 'mysql',
 	$db_host = 'localhost',
 	$db_name = 'bugzilla',
  	$db_user = 'bugzilla',
  	$db_pass = '',
  	$db_port = 0,
  	$db_sock = '',
  	$db_check = true,
  	$index_html = false,
  	$cvsbin = '/usr/bin/cvs',
  	$interdiffbin = '/usr/bin/interdiff',
  	$diffpath = '/usr/bin',
  	$site_wide_secret = '',
	$smtp_server = 'localhost'